---
title: "Module 7 Group 8"
author: 'Helena Ebeling, Layne Kiratsous, Sofia Rugova '
date: "2024-11-19"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
library(rgbif)
library(kableExtra)
library(tidyverse)
library(MuMIn)
library(knitr)
library(devtools)
library(rnoaa)
library(data.table)
library(ggmap)
library(usmap)
library(magick)
library(cowplot)
library(lme4)
library(car)
library(dplyr)
library(ggplot2)
library(lubridate)
library(parallel)
library(data.table)
```

```{r}
species <- c("Myiarchus crinitus","Icterus galbula","Pheucticus ludovicianus","Coccyzus americanus","Setophaga caerulescens")
years <- 2000:2019
months <- c(4, 5) # April and May

fetch_data_for_species_year <- function(species, year) {
occ_data(
scientificName = species,
year = year,
month = months,
limit = 5000,
country = "US",
basisOfRecord = "HUMAN_OBSERVATION",
stateProvince = "Massachusetts"
)[[2]] # Extract the data slot
}

#fetch data for one species across all years
fetch_data_for_species <- function(species) {
results <- mclapply(years, function(year) {
fetch_data_for_species_year(species, year)
}, mc.cores = detectCores() - 1)

#combine results into one data.table
dat <- rbindlist(results, fill = TRUE)
}

#data for all species, one species at a time
dat <- rbindlist(lapply(species, fetch_data_for_species), fill = TRUE)


```



```{r,map}
options(noaakey = "jggxsGpVSUlkFWePhWMDgZpUJhKVXUJE") #INPUT YOUR TOKEN!

sts <- c("GHCND:USW00013894","GHCND:USW00013881","GHCND:USW00014739")

sta.d <- bind_rows(
  lapply(sts, function(x) ncdc_stations(stationid = x)$data)
) %>%
  mutate(usmap_transform(., input_names = c("longitude", "latitude"))) %>%
  mutate(name = str_sub(name, -5, -4)) %>%
  mutate(migr.day = c(10, 5, 0)) %>%
  separate(id, into = c("station.type", "id"))

sta.d1 <- sta.d %>%
  sf::st_as_sf() %>%
  sf::st_coordinates()

sta.d<- cbind(sta.d, sta.d1)


plot_usmap(include = c(.northeast_region,.south_region,.east_north_central))+geom_point(data=sta.d,aes(X,Y,col=name))

weather.d <- meteo_pull_monitors(sta.d$id,date_min = "2000-01-01")

```

```{r, weather}
weather.d <- weather.d%>%
  mutate(year=as.integer(str_sub(date,1,4)), date=as.Date(date))%>%
  group_by(year)%>%
  mutate(j.day=julian(date,origin=as.Date(paste0(unique(year),"-01-01"))),date2=date,wdir.rad=(180-abs(wdf2-180))*pi/180,wvec=cos(wdir.rad)*-1*awnd)%>%
  dplyr::select(id,year,date2,j.day,tmin,tmax,wvec)%>%
  left_join(sta.d%>%select(id,name,migr.day))%>%
  mutate(j.day=j.day+migr.day)
```


```{r, analyze}
mc <- dat %>%
  filter(species %in% c("Myiarchus crinitus", "Icterus galbula", "Pheucticus ludovicianus", "Coccyzus americanus", "Setophaga caerulescens")) %>%
  group_by(year) %>%
  mutate(date = as.Date(paste0(year, "-", month, "-", day)),
         j.day = julian(date, origin = as.Date(paste0(unique(year), "-01-01")))) %>%
  group_by(species, year, j.day, date) %>%
  summarise(day.tot = sum(individualCount, na.rm = TRUE)) %>%
  group_by(species, year) %>%
  mutate(prop = cumsum(day.tot / sum(day.tot, na.rm = TRUE))) %>%
  filter(year > 1999)


mc.pred <- mc%>%
  group_by(year)%>%
  summarize(pred=predict(nls(prop~SSlogis(j.day,Asym, xmid, scal)),newdata=data.frame(j.day=min(j.day):max(j.day))),
            j.day=min(j.day):max(j.day),)%>%
  left_join(mc%>%dplyr::select(j.day,date))

mc.arrive.date <-mc.pred%>%
  group_by(year)%>%
  filter(j.day==j.day[which.min(abs(pred-0.25))])

mc.arrive.date%>%
  ggplot(aes(year,j.day))+geom_point()

mc.arr.weath <- mc.arrive.date%>%
  left_join(weather.d)%>%
  left_join(mc%>%dplyr::select(year,date,j.day))

weather.wk <-weather.d %>%
  group_by(year,name) %>%
  mutate(wk.tmin = frollmean(tmin, n=14,align="right"),
         wk.tmax = frollmean(tmax, n=14,align="right"),
         wk.wvec = frollmean(wvec, n=14,align="right"))%>%
  dplyr::select(j.day,date2,name,wk.tmin,wk.tmax,wk.wvec)

mc.arr.weath2 <- mc.arrive.date%>%
  left_join(weather.wk)


head(mc.arr.weath2)
```

```{r, lmer}
mc.lmer <- lmer(j.day~tmin*tmax*wvec+(1|name),mc.arr.weath,na.action = "na.fail")
Anova(mc.lmer)

mc.lmer2 <- lmer(j.day~wk.tmin*wk.tmax*wk.wvec+(1|name),mc.arr.weath2,na.action = "na.fail")
Anova(mc.lmer2) 

mc.arr.aic <- dredge(mc.lmer2,fixed = c("wk.tmin","wk.tmax","wk.wvec"),)

mc.kb <- kable(mc.arr.aic[1:4,],caption = "Fit values for nested models of the most complicated lme model")

kable_styling(mc.kb)

best.lmer <-  lmer(j.day~wk.tmin+wk.tmax+wk.wvec+(1|name),mc.arr.weath2,na.action = "na.fail")

Anova(best.lmer)
```

